name: Add docs-reviewers request to the docs-content review board

# **What it does**: Adds PRs in github/github and github/audit-log-allowlists that requested a review from docs-reviewers to the docs-content review board
# **Why we have it**: To catch docs-reviewers requests in github/github and github/audit-log-allowlists
# **Who does it impact**: docs-content maintainers

on:
  workflow_dispatch:
  schedule:
    - cron: '20 */6 * * *' # Run every 6 hours at 20 minutes after

permissions:
  contents: read

jobs:
  add-requests-to-board:
    name: Add requests to board
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo content
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Run script for github
        run: |
          node src/workflows/fr-add-docs-reviewers-requests.js
        env:
          TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
          PROJECT_NUMBER: 2936
          ORGANIZATION: 'github'
          REPO: 'github'
          REVIEWER: 'docs-reviewers'
          FEATURE: 'OpenAPI schema update'

      - name: Run script for audit-log-allowlists
        run: |
          node src/workflows/fr-add-docs-reviewers-requests.js
        env:
          TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
          PROJECT_NUMBER: 2936
          ORGANIZATION: 'github'
          REPO: 'audit-log-allowlists'
          REVIEWER: 'docs-reviewers'
          FEATURE: 'Audit log event descriptions'
